FROM nginx:alpine

ENV NGINX_ENVSUBST_OUTPUT_DIR /etc/nginx

ENV PROXY_PASS_URL ${PROXY_PASS_URL}
ENV WORKER_PROCESSES ${WORKER_PROCESSES:-2}
ENV WORKER_CONNECTIONS ${WORKER_CONNECTIONS:-1024}
ENV CACHE_SIZE ${CACHE_SIZE:-3g}

ADD  nginx.conf  /etc/nginx/templates/nginx.conf.template